#!/bin/zsh

#------------
# Use this script to fix the error with compinit that sometimes appear when opening zsh:
# zsh compinit: insecure directories, run compaudit for list.
# Ignore insecure directories and continue [y] or abort compinit [n]?
#
# Reference: https://stackoverflow.com/questions/13762280/zsh-compinit-insecure-directories/41674919#41674919
#------------

sudo chmod -R 755 /usr/local/share/zsh/site-functions
sudo chmod -R 755 /usr/local/share/zsh