#!/bin/bash

openemu_path="${HOME}/Library/Application Support/OpenEmu/"
backup_path="${HOME}/OneDrive/Games"
backup_filename="${backup_path}/OpenEmuLibrary.zip"

if [[ -f "$backup_filename" ]]; then
    echo "Clearing existing backup..."
    rm $backup_filename
fi

echo "Compressing the OpenEmu Library..."
zip -r $backup_filename "$openemu_path"
echo "Compressed file saved to ${backup_filename}."