#!/bin/bash

# create_script
# This scritp creates a new bash script, sets permissions and more
# Author: ravero

# Is there an argument?
if [[ ! $1 ]]; then
	echo "Missing argument"
	exit 1
fi

# Check open editor option
declare open_editor=""
getopts "e" opt && [[ $opt = "e" ]] && open_editor="true"
shift $(( OPTIND -1 ))

if [[ $# -eq 1 && $open_editor ]]; then
	open_editor="true"
fi

declare -r bindir="${HOME}/bin"

# Check bin directory exists
if [[ ! -d $bindir ]]; then
	#if not: Create bin directory
	if mkdir "$bindir"; then
		echo "created ${bindir}" >&2
	else
		echo "Could not create ${bindir}." >&2
		exit 1
	fi
fi

while [[ $1 ]]; do
	scriptname="$1"
	filename="${bindir}/${scriptname}"

	if [[ -e $filename ]]; then
		echo "File ${filename} already exists" >&2
		shift
		continue
	fi

	if type "$scriptname" > /dev/null 2>&1; then
		echo "There is already a command with name ${scriptname}"
		shift
		continue
	fi

	# Create a script with a single line
	echo '#!/bin/bash' > "$filename"
	# Add executable permission
	chmod +x "$filename"

	shift
done

# Open with editor
if [[ $open_editor ]]; then
	echo opening
	if [[ $EDITOR ]]; then
		$EDITOR "$filename"
	else
		echo "Script created; not starting editor because \$EDITOR is not set."
	fi
fi

exit 0
