#!/bin/bash

app_support_path="${HOME}/Library/Application Support/"
backup_path="${HOME}/OneDrive/Games"
backup_filename="${backup_path}/OpenEmuLibrary.zip"

if [[ -f "$backup_filename" ]]; then
    echo "Clearing existing backup..."
    rm $backup_filename
fi

echo "Compressing the OpenEmu Library..."
(cd "$app_support_path"; zip -r $backup_filename ./OpenEmu/)
echo "Compressed file saved to ${backup_filename}."