#!/bin/bash

## Essential
mas install 1333542190	        # 1Password
mas install 937984704           # Amphetamine

## Developer Tools
mas install 497799835           # Xcode
mas install 1450874784          # Transporter
mas install 1294179975          # AppIconBuilder
mas install 1178548760          # Resdroid
mas install 1388020431          # DevCleaner
mas install 768053424           # Gapplin
mas install 640199958		    # Apple Developer

## Install Office Apps
mas install 462054704           # Microsoft Word
mas install 462058435           # Microsoft Excel
mas install 462062816           # Microsoft PowerPoint
mas install 784801555           # Microsoft OneNote
mas install 985367838           # Microsoft Outlook
mas install 823766827           # OneDrive
mas install 1274495053          # Microsoft To Do

## iWork
mas install 409201541           # Pages
mas install 409203825           # Numbers
mas install 409183694           # Keynote

## Utilities
mas install 1153157709          # Speedtest
mas install 1333277187          # Disconnect Premium
mas install 411643860           # DaisyDisk
mas install 549083868           # Display Menu
mas install 430255202           # Mactracker
mas install 1463361068		    # Exchange Rates 3

## Others
mas install 449155338           # SomaFM
mas install 406056744           # Evernote
mas install 1481669779          # Evernote Web Clipper
mas install 405399194           # Kindle
mas install 1310686187          # Scrivener 3
mas install 747648890           # Telegram
mas install 803453959           # Slack
mas install 1477385213          # Save to Pocket
mas install 568494494           # Pocket
mas install 1473726602          # Tab Space

## Legacy
#mas install 1384080005          # Tweetbot
#mas install 407963104           # Pixelmator - was on the previous family account
