#!/bin/bash

# Homebrew Casks
## Regular apps
brew cask install android-studio
brew cask install alfred
brew cask install azure-data-studio
brew cask install blue-jeans
brew cask install discord
brew cask install docker
brew cask install firefox
brew cask install fork
brew cask install gitkraken
brew cask install google-chrome
brew cask install handbrake
brew cask install imazing
brew cask install itsycal
brew cask install keyboard-cleaner
brew cask install parallels
brew cask install postman
brew cask install reflector
brew cask install selfcontrol
brew cask install skype
brew cask install staruml
brew cask install upwork
brew cask install visual-studio-code
brew cask install vlc
brew cask install tunnelblick
brew cask install whatsapp
brew cask install zeplin
brew cask install iterm2

## Casks Distributed as packages required typing password, so they're moved last
brew cask install sf-symbols
brew cask install microsoft-azure-storage-explorer
brew cask install microsoft-edge
brew cask install microsoft-teams
brew cask install powershell
brew cask install skype-for-business
brew cask install oracle-jdk
brew cask install choosy

## Quicklook Plugins
brew cask install qlcolorcode 
brew cask install qlstephen
brew cask install qlmarkdown
brew cask install quicklook-json
brew cask install qlimagesize
brew cask install suspicious-package
brew cask install provisionql quicklookapk

## Legacy
#brew cask install zoomus 		# Stopped using zoom.us
