#!/bin/bash

#------------------------------------------------------------------------------
# Setup Scripts
# 07 - Network Setup
#
# This script will set defaults for network connections on the computer.
# Check if the Network Services apply correctly. If you need to list use:
#
#   networksetup -listallnetworkservices
#
# Then update the script apropriately.
#------------------------------------------------------------------------------

echo "Setting DNS Servers for Wi-Fi and Display Ethernet network services..."
networksetup -setdnsservers "Wi-Fi" 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001 
networksetup -setdnsservers "Display Ethernet" 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001
echo "Settings applied!"

echo ""
echo "Wi-Fi DNS Servers:"
networksetup -getdnsservers "Wi-Fi"

echo ""
echo "Display Ethernet DNS Servers:"
networksetup -getdnsservers "Display Ethernet"